### Site Settings ###
title: Aryan Kadiya
description: >-
            Understanding technology and people are the
            most important skills, so investing time in 
            expading my technical knowledge and human 
            psychology and philosophy.
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: ak523/ak523.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)

### Plugins ###
#plugins:
#  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/thanks.html
  - pages/blog.html

### Author Info ###
author:
  name: Aryan Kadiya
  image: https://media-exp1.licdn.com/dms/image/C5103AQGfTvh6lZXfqw/profile-displayphoto-shrink_800_800/0/1585042399319?e=1637798400&v=beta&t=PJ9CU-q1tpWMCkO4ycpLuSSXG3A6WNNe3EDlBRd_Hqk
  email: aryankadiya@gmail.com
  linkedin: aryan-kadiya
  github: ak523
  # kaggle: nilavanakilan

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###
disqus:
  shortname: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
